name: pr-basics demo


on:
    pull_request:
        types: [opened, synchronize, closed]

jobs:
    action-check:
        runs-on: ubuntu-latest
        steps:
            - name: print the action name
              run: echo "This event was created by action ${{ github.event_name }}"